"""Script for training an MEG-GPT model on the resting-state CamCAN data.

The generator is trained on tokenized data generated by the best 
tokenizer run on the resting-state MEG data for each tokenizer type.
"""

# Import packages
import os
from sys import argv
from osl_dynamics.data import load_tfrecord_dataset
from osl_dynamics.inference import tf_ops
from osl_dynamics.utils import set_random_seed
from osl_foundation import create_model


if __name__ == "__main__":
    # ---------- User Inputs ---------- #
    # Set GPU memory growth
    tf_ops.gpu_growth()

    # Set user arguments
    if len(argv) != 5:
        raise ValueError(
            "Please provide the model type, best tokenizer run ID, " +
            "generator run ID, and epoch index as arguments."
        )
    model_type = argv[1]
    tk_run_id = int(argv[2])
    gt_run_id = int(argv[3])
    epoch_idx = int(argv[4])
    print(f"[INFO] Model Type: {model_type} | Best Tokenizer Run ID: {tk_run_id} " + 
          f"| Generator Run ID: {gt_run_id} | Epoch: {epoch_idx}")
    
    # Set random seed for Python random, NumPy, and TensorFlow
    BASE_SEED = 813
    set_random_seed(BASE_SEED + epoch_idx, op_determinism=False)
    # NOTE: This ensures same initialization across different model types
    #       at epoch 0; later epochs will restore from checkpoints.

    # ---------- Directories ---------- #
    BASE_DIR = "/well/woolrich/users/olt015/Cho2026_Tokenizer"
    DATA_DIR = os.path.join(BASE_DIR, "tokenized_data_tfrecords")
    MODEL_DIR = os.path.join(BASE_DIR, "models/generator")

    data_dir = f"{DATA_DIR}/{model_type}/{tk_run_id}"
    generator_dir = f"{MODEL_DIR}/{model_type}/{gt_run_id}"
    os.makedirs(generator_dir, exist_ok=True)

    # ---------- Build Generator ---------- #
    generator = create_model(f"{generator_dir}/config.yml")
    generator.summary()

    # ---------- Load data ---------- #
    train_data, val_data = load_tfrecord_dataset(
        data_dir,
        batch_size=generator.config.training_config.batch_size,
        shuffle=True,  # applies for train set only
        concatenate=True,
        drop_last_batch=True,
        buffer_size=2000,
    )

    # ---------- Fit generator ---------- #
    generator.fit(
        train_data,
        validation_data=val_data,
        tokenize=False,
    )

    print("Generator training complete.")
